# mb2_bees_varroas.yaml file

net: mb2-ssd-lite 
trained_model: models/index-dataset/mb2_bees_varroas/mb2-ssd-lite-Epoch-135-Loss-2,6243468523025513.pth #mb2-ssd-lite-Epoch-30-Loss-3,513983130455017.pth #mb2-ssd-lite-Epoch-50-Loss-3,10933780670166.pth #mb2-ssd-lite-Epoch-100-Loss-2,7263399958610535.pth #mb2-ssd-lite-Epoch-135-Loss-2,6243468523025513.pth
dataset_type: index 
dataset: /media/pc-neuron/Data/Lukas/PHD_Industry_Anomaly/Bee_project/new_no_index/labels_b_v
label_file: models/index-dataset/mb2_bees_varroas/index-model-labels.txt 
eval_dir: eval_results/index-dataset/mb2_bees_varroas
